apiVersion: template.openshift.io/v1
kind: Template
labels:
metadata:
  annotations:
  labels:
  name: ${APPLICATION_NAME}-${SECRET_NAMESPACE}-secret-template
  namespace: ${TARGET_NAMESPACE}
objects:
- apiVersion: v1
  data:
    ssh-privatekey: <data kept in a vault>
  kind: Secret
  metadata:
    name: ${SECRET_NAME}
    namespace: ${TARGET_NAMESPACE}
  type: kubernetes.io/ssh-auth
parameters:
- description: The secret name.
  displayName: The secret name
  name: SECRET_NAME
  required: true
  value: git-ssh
- description: The target namespace for object list.
  displayName: Target namespace
  name: TARGET_NAMESPACE
  required: true
  value: appteam1-demo-dev
