apiVersion: v1
kind: Secret
metadata:
  annotations:
  name: petclinic
stringData:
  database-name: <data kept in a vault>
  database-password: <data kept in a vault>
  database-user: <data kept in a vault>
  database-uri: <data kept in a vault>
