name: Context to Env Vars
on:
  workflow_dispatch:
    inputs:
      GARBAGE_PARM:
        required: true
        type: string
jobs:
  contexttoenvvars:
    name: contextToEnvVars
    environment: smbc-dev
    runs-on: [self-hosted, k8s-tools]

    steps:
      - name: Expose github environment as shell variables
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          to_envs() { jq -r "to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""; }
          echo "$SECRETS_CONTEXT" | to_envs >> $GITHUB_ENV
