name: Install Secret
on:
  workflow_dispatch:
    inputs:
      SECRET_NAME:
        required: true
        type: string
#####################################################################################
##                                                                                 ##
## requirements: secret template must have placeholders and parameters for         ##
##               secret name and namespace.                                        ##
##                                                                                 ##
##               template should be parameterized where data elements are          ##
##               defined in the parameter list.                                    ##
##                                                                                 ##
#####################################################################################
jobs:
  installsecret:
    name: installSecret
    environment: smbc-dev
    runs-on: [self-hosted, k8s-tools]

    steps:
      - name: Install Secret
#       env:
#         JSON: ${{ toJSON(secrets) }}
        run: |
          cp /home/runner/generate_uuid.py .
          uuid=$(python3 ./generate_uuid.py)
          secret_key=${{ inputs.SECRET_NAME }}
          echo ${{ toJSON(secrets) }} | tr -d '\n' > ./$uuid.json
          raw_secret_data=$(cat $uuid.json | grep $secret_key | cut -f2 -d: | tr -d ,)
          echo "raw_secret_data before decode: $raw_secret_data"
          secret_data=$( echo $raw_secret_data | base64 -d )
          echo "secret_data: $secret_data"
          template_name=$uuid".yaml"
          echo "$secret_data" > ./$template_name
