name: Install Secret
on:
  workflow_dispatch:
    inputs:
      SECRET_NAME:
        required: true
        type: string
#####################################################################################
##                                                                                 ##
## requirements: secret template must have placeholders and parameters for         ##
##               secret name and namespace.                                        ##
##                                                                                 ##
##               template should be parameterized where data elements are          ##
##               defined in the parameter list.                                    ##
##                                                                                 ##
#####################################################################################
jobs:
  installsecret:
    name: installSecret
    environment: smbc-dev
    runs-on: [self-hosted, k8s-tools]

    steps:
      - name: Install Secret
        run: |
          secret_key=${{ inputs.SECRET_NAME }}

          SECRET_DATA="$(jq -r --arg secret_key "$secret_key" '.[$secret_key]' <<'JSON' \
          ${{ toJSON(secrets) }} \
          JSON \
          )"
          uuid=$(python3 ./generate_uuid.py)
          template_name=$uuid".yaml"
          echo "$SECRET_DATA" > ./$template_name
