name: Install Secret
on:
  workflow_dispatch:
    inputs:
      SECRET_NAME:
        required: true
        type: string
#####################################################################################
##                                                                                 ##
## requirements: secret template must have placeholders and parameters for         ##
##               secret name and namespace.                                        ##
##                                                                                 ##
##               template should be parameterized where data elements are          ##
##               defined in the parameter list.                                    ##
##                                                                                 ##
##               template MUST be base64 encoded before setting github secret      ##
##               eg. cat ./.openshift/templates/secret.yaml | base64 -i -w 0       ##
##                                                                                 ##
#####################################################################################
jobs:
  installsecret:
    name: installSecret
    environment: smbc-dev
    runs-on: [self-hosted, k8s-tools]

    steps:
      - name: Install Secret
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          cp /home/runner/generate_uuid.py .
          uuid=$(python3 ./generate_uuid.py)
          secret_key=${{ inputs.SECRET_NAME }}
          echo "$SECRETS_CONTEXT" > ./$uuid.json
          raw_secret_data=$(cat $uuid.json | grep $secret_key | cut -f2 -d: | tr -d \" | tr -d ' ' | tr -d ,)
          echo "raw_secret_data before decode: $raw_secret_data"
          secret_data=$( echo $raw_secret_data | base64 -di )
          echo "secret_data: $secret_data"
          template_name=$uuid".yaml"
          echo "$secret_data" > ./$template_name
          oc login --token ${{ secrets.OC_SA_TOKEN }} ${{ vars.OC_API_URL }}
          oc process -f ./$template_name | oc apply -f-
          oc logout
