name: Install Secret
on:
  workflow_dispatch:
    inputs:
      SECRET_NAME:
        required: true
        type: string
#####################################################################################
##                                                                                 ##
## requirements: secret template must have placeholders and parameters for         ##
##               secret name and namespace.                                        ##
##                                                                                 ##
##               template should be parameterized where data elements are          ##
##               defined in the parameter list.                                    ##
##                                                                                 ##
#####################################################################################
jobs:
  installsecret:
    name: installSecret
    environment: smbc-dev
    runs-on: [self-hosted, k8s-tools]

    steps:
      - name: Install Secret
        env:
          JSON: ${{ toJSON(secrets }}
        run: |
          secret_key=${{ inputs.SECRET_NAME }}
          secret_data=$( echo -n ${{ env.JSON }} | jq .$secret_key )
          cp /home/runner/generate_uuid.py .
          uuid=$(python3 ./generate_uuid.py)
          template_name=$uuid".yaml"
          echo "$secret_data" > ./$template_name
