name: Install Secret
on:
  workflow_dispatch:
    inputs:
      SECRET_NAME:
        required: true
        type: string
#####################################################################################
##                                                                                 ##
## requirements: secret template must have placeholders and parameters for         ##
##               secret name and namespace.                                        ##
##                                                                                 ##
##               template should be parameterized where data elements are          ##
##               defined in the parameter list.                                    ##
##                                                                                 ##
#####################################################################################
jobs:
  installsecret:
    name: installSecret
    environment: smbc-dev
    runs-on: [self-hosted, k8s-tools]

    steps:
      - name: Install Secret
        env:
          TEMPLATE_KEY: ${{ inputs.SECRET_NAME }}
        run: |
          secret_data=secrets[env.TEMPLATE_KEY]
          echo "secret_data before decode: $secret_data"
          secret_data=$( echo $secret_data | base64 -d )
          cp /home/runner/generate_uuid.py .
          uuid=$(python3 ./generate_uuid.py)
          echo "secret_data: $secret_data"
          template_name=$uuid".yaml"
          echo "$secret_data" > ./$template_name
