name: Say Hello
on:
  push:
    branches:
      - main # the name of your main branch
  workflow_dispatch:
    inputs:
      USER_NAME:
        required: true
        type: string
jobs:
  sayhello:
    name: SayHello
    environment: smbc-dev
    runs-on: [self-hosted, k8s-tools]
    env: 
      SECRET_MANIFEST: ${{ secrets.K8S_DEV_SECRET_INIT_DB_AUTH }}
    steps:
      - name: Say Hello
        run: |
          echo "Hello!!!"
          echo "${{ secrets.K8S_DEV_SECRET_INIT_DB_AUTH }}" > ./secret.yaml
          cat ./secret.yaml
